server:
  port: 8081

keycloak:
  realm: TMS App Server
  auth-server-url: http://localhost:8080/auth
  resource: tms-client
  public-client: true
  bearer-only: true
  #ssl-required: external
  #use-resource-role-mappings: true